In [1]:
import pandas as pd
header=['erythema','scaling','definite borders','itching','koebner phenomenon','polygonal papules','follicular papules','oral mucosal involvement','knee and elbow involvement','scalp involvement','family history','melanin incontinence','eosinophils in the infiltrate','PNL infiltrate','fibrosis of the papillary dermis','exocytosis','acanthosis','hyperkeratosis','parakeratosis','clubbing of the rete ridges','elongation of the rete ridges','thinning of the suprapapillary epidermis','spongiform pustule','munro microabcess','focal hypergranulosis','disappearance of the granular layer','vacuolisation and damage of basal layer','spongiosis','saw-tooth appearance of retes','follicular horn plug','perifollicular parakeratosis','inflammatory monoluclear inflitrate','band-like infiltrate','Age','Type of disease']
df = pd.read_csv('C:\\Users\\Talha Habib\\Downloads\\dermatology.data',header=None,names=header)
print(df)

     erythema  scaling  definite borders  itching  koebner phenomenon  \
0           2        2                 0        3                   0   
1           3        3                 3        2                   1   
2           2        1                 2        3                   1   
3           2        2                 2        0                   0   
4           2        3                 2        2                   2   
..        ...      ...               ...      ...                 ...   
361         2        1                 1        0                   1   
362         3        2                 1        0                   1   
363         3        2                 2        2                   3   
364         2        1                 3        1                   2   
365         3        2                 2        0                   0   

     polygonal papules  follicular papules  oral mucosal involvement  \
0                    0                   0         

In [13]:
k=df.iloc[:,33].values
print(k)

['55' '8' '26' '40' '45' '41' '18' '57' '22' '30' '20' '21' '22' '10' '65'
 '40' '30' '38' '23' '17' '8' '51' '42' '44' '22' '33' '10' '17' '43' '50'
 '50' '10' '34' '?' '?' '?' '?' '15' '26' '46' '51' '62' '15' '35' '30'
 '48' '46' '12' '52' '60' '32' '35' '41' '48' '51' '19' '22' '29' '25'
 '33' '8' '40' '33' '42' '36' '60' '36' '21' '40' '21' '34' '13' '52' '48'
 '17' '25' '33' '62' '52' '27' '40' '31' '27' '10' '55' '30' '42' '48'
 '22' '31' '50' '43' '30' '42' '22' '18' '35' '60' '28' '13' '20' '64'
 '43' '20' '34' '39' '60' '38' '44' '36' '41' '18' '39' '40' '47' '16'
 '27' '52' '25' '0' '33' '46' '7' '30' '29' '23' '8' '44' '17' '16' '55'
 '40' '34' '29' '34' '25' '70' '37' '41' '32' '20' '19' '61' '27' '36'
 '40' '52' '27' '30' '45' '34' '27' '46' '52' '28' '40' '55' '32' '33'
 '47' '35' '61' '22' '10' '20' '55' '67' '51' '20' '22' '45' '55' '56'
 '18' '40' '30' '33' '40' '42' '36' '27' '56' '60' '20' '7' '30' '19' '52'
 '55' '23' '50' '38' '25' '18' '35' '22' '52' '50' '33' '4

In [14]:
X=df.drop("Type of disease",axis="columns")
X=df.drop("Age",axis="columns")
Y=df["Type of disease"]

In [15]:
from sklearn.impute import SimpleImputer
x=SimpleImputer(missing_values="?",strategy="most_frequent")
i=k.reshape(-1,1)
i=x.fit_transform(i)
k=i.reshape(-1)
X["Age"]=k
print(X)

     erythema  scaling  definite borders  itching  koebner phenomenon  \
0           2        2                 0        3                   0   
1           3        3                 3        2                   1   
2           2        1                 2        3                   1   
3           2        2                 2        0                   0   
4           2        3                 2        2                   2   
..        ...      ...               ...      ...                 ...   
361         2        1                 1        0                   1   
362         3        2                 1        0                   1   
363         3        2                 2        2                   3   
364         2        1                 3        1                   2   
365         3        2                 2        0                   0   

     polygonal papules  follicular papules  oral mucosal involvement  \
0                    0                   0         

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.4)
X2_train,X2_test,Y2_train,Y2_test=train_test_split(X,Y,test_size=0.3)
X3_train,X3_test,Y3_train,Y3_test=train_test_split(X,Y,test_size=0.2)

In [17]:
from sklearn.naive_bayes import MultinomialNB
m=MultinomialNB()
m1=m.fit(X_train,Y_train)
m2=m.fit(X2_train,Y2_train)
m3=m.fit(X3_train,Y3_train)
y1=m.predict(X_test)
y2=m.predict(X2_test)
y3=m.predict(X3_test)

In [18]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
r=classification_report(Y_test,y1)
r2=accuracy_score(Y_test,y1)
r3=confusion_matrix(Y_test,y1)
re=classification_report(Y2_test,y2)
re2=accuracy_score(Y2_test,y2)
re3=confusion_matrix(Y2_test,y2)
res=classification_report(Y3_test,y3)
res2=accuracy_score(Y3_test,y3)
res3=confusion_matrix(Y3_test,y3)


print(r)
print(r2)
print(r3)
print(re)
print(re2)
print(re3)
print(res)
print(res2)
print(res3)
## we are getting good best accuracy when our test_size is small 


              precision    recall  f1-score   support

           1       1.00      1.00      1.00        45
           2       1.00      0.94      0.97        17
           3       1.00      1.00      1.00        36
           4       0.95      1.00      0.98        20
           5       1.00      1.00      1.00        24
           6       1.00      1.00      1.00         5

    accuracy                           0.99       147
   macro avg       0.99      0.99      0.99       147
weighted avg       0.99      0.99      0.99       147

0.9931972789115646
[[45  0  0  0  0  0]
 [ 0 16  0  1  0  0]
 [ 0  0 36  0  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 24  0]
 [ 0  0  0  0  0  5]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       1.00      0.90      0.95        20
           3       1.00      1.00      1.00        26
           4       0.90      1.00      0.95        18
           5       1.00      1.00      1

In [26]:
from sklearn.model_selection import KFold
kd = KFold(2, True) 
for train,test in kd.split(X_train):
    print(x_tr[train],x_tr[test])
        

[  0   1   3   4   5   9  10  16  17  19  20  21  25  26  27  28  30  31
  33  35  36  40  43  44  47  48  49  50  51  55  57  58  59  62  64  66
  67  72  73  74  76  77  78  79  80  82  84  86  91  92  96  97 101 104
 107 108 110 111 114 115 118 120 122 123 124 125 131 132 134 135 138 139
 142 147 150 153 155 159 161 163 166 167 168 169 175 177 178 179 181 183
 185 188 189 190 192 193 195 197 199 200 201 207 210 212 213 214 216 217
 218] [  2   6   7   8  11  12  13  14  15  18  22  23  24  29  32  34  37  38
  39  41  42  45  46  52  53  54  56  60  61  63  65  68  69  70  71  75
  81  83  85  87  88  89  90  93  94  95  98  99 100 102 103 105 106 109
 112 113 116 117 119 121 126 127 128 129 130 133 136 137 140 141 143 144
 145 146 148 149 151 152 154 156 157 158 160 162 164 165 170 171 172 173
 174 176 180 182 184 186 187 191 194 196 198 202 203 204 205 206 208 209
 211 215]
[  2   6   7   8  11  12  13  14  15  18  22  23  24  29  32  34  37  38
  39  41  42  45  46  52  53  54  5