In [101]:
import pandas as pd
header=['erythema','scaling','definite borders','itching','koebner phenomenon','polygonal papules','follicular papules','oral mucosal involvement','knee and elbow involvement','scalp involvement','family history','melanin incontinence','eosinophils in the infiltrate','PNL infiltrate','fibrosis of the papillary dermis','exocytosis','acanthosis','hyperkeratosis','parakeratosis','clubbing of the rete ridges','elongation of the rete ridges','thinning of the suprapapillary epidermis','spongiform pustule','munro microabcess','focal hypergranulosis','disappearance of the granular layer','vacuolisation and damage of basal layer','spongiosis','saw-tooth appearance of retes','follicular horn plug','perifollicular parakeratosis','inflammatory monoluclear inflitrate','band-like infiltrate','Age','Type of disease']
df = pd.read_csv('C:\\Users\\Talha Habib\\Downloads\\dermatology.data',header=None,names=header)
print(df)

     erythema  scaling  definite borders  itching  koebner phenomenon  \
0           2        2                 0        3                   0   
1           3        3                 3        2                   1   
2           2        1                 2        3                   1   
3           2        2                 2        0                   0   
4           2        3                 2        2                   2   
..        ...      ...               ...      ...                 ...   
361         2        1                 1        0                   1   
362         3        2                 1        0                   1   
363         3        2                 2        2                   3   
364         2        1                 3        1                   2   
365         3        2                 2        0                   0   

     polygonal papules  follicular papules  oral mucosal involvement  \
0                    0                   0         

In [102]:
y=df.iloc[:,33].values
X=df.drop(['Type of disease','Age'],axis='columns')
Y=df["Type of disease"]
print(y)


['55' '8' '26' '40' '45' '41' '18' '57' '22' '30' '20' '21' '22' '10' '65'
 '40' '30' '38' '23' '17' '8' '51' '42' '44' '22' '33' '10' '17' '43' '50'
 '50' '10' '34' '?' '?' '?' '?' '15' '26' '46' '51' '62' '15' '35' '30'
 '48' '46' '12' '52' '60' '32' '35' '41' '48' '51' '19' '22' '29' '25'
 '33' '8' '40' '33' '42' '36' '60' '36' '21' '40' '21' '34' '13' '52' '48'
 '17' '25' '33' '62' '52' '27' '40' '31' '27' '10' '55' '30' '42' '48'
 '22' '31' '50' '43' '30' '42' '22' '18' '35' '60' '28' '13' '20' '64'
 '43' '20' '34' '39' '60' '38' '44' '36' '41' '18' '39' '40' '47' '16'
 '27' '52' '25' '0' '33' '46' '7' '30' '29' '23' '8' '44' '17' '16' '55'
 '40' '34' '29' '34' '25' '70' '37' '41' '32' '20' '19' '61' '27' '36'
 '40' '52' '27' '30' '45' '34' '27' '46' '52' '28' '40' '55' '32' '33'
 '47' '35' '61' '22' '10' '20' '55' '67' '51' '20' '22' '45' '55' '56'
 '18' '40' '30' '33' '40' '42' '36' '27' '56' '60' '20' '7' '30' '19' '52'
 '55' '23' '50' '38' '25' '18' '35' '22' '52' '50' '33' '4

In [103]:
from sklearn.impute import SimpleImputer
import numpy as n
im=SimpleImputer(missing_values='?',strategy="most_frequent")
h=y.reshape(-1,1)
k=im.fit_transform(h)
y=k.reshape(-1)
X["Age"]=y

In [128]:
print(X.iloc[:,33].values)

['55' '8' '26' '40' '45' '41' '18' '57' '22' '30' '20' '21' '22' '10' '65'
 '40' '30' '38' '23' '17' '8' '51' '42' '44' '22' '33' '10' '17' '43' '50'
 '50' '10' '34' '40' '40' '40' '40' '15' '26' '46' '51' '62' '15' '35'
 '30' '48' '46' '12' '52' '60' '32' '35' '41' '48' '51' '19' '22' '29'
 '25' '33' '8' '40' '33' '42' '36' '60' '36' '21' '40' '21' '34' '13' '52'
 '48' '17' '25' '33' '62' '52' '27' '40' '31' '27' '10' '55' '30' '42'
 '48' '22' '31' '50' '43' '30' '42' '22' '18' '35' '60' '28' '13' '20'
 '64' '43' '20' '34' '39' '60' '38' '44' '36' '41' '18' '39' '40' '47'
 '16' '27' '52' '25' '0' '33' '46' '7' '30' '29' '23' '8' '44' '17' '16'
 '55' '40' '34' '29' '34' '25' '70' '37' '41' '32' '20' '19' '61' '27'
 '36' '40' '52' '27' '30' '45' '34' '27' '46' '52' '28' '40' '55' '32'
 '33' '47' '35' '61' '22' '10' '20' '55' '67' '51' '20' '22' '45' '55'
 '56' '18' '40' '30' '33' '40' '42' '36' '27' '56' '60' '20' '7' '30' '19'
 '52' '55' '23' '50' '38' '25' '18' '35' '22' '52' '50' '33

In [129]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [130]:
from sklearn.neighbors import KNeighborsClassifier
c=KNeighborsClassifier(n_neighbors=7)
c.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [131]:
Y_pre=c.predict(X_test)
print(Y_pre)

[1 3 1 1 3 1 4 1 5 1 4 1 2 3 1 3 3 6 4 4 1 3 5 1 3 2 2 2 1 1 2 5 2 3 4 2 6
 2 2 4 1 5 3 3 3 2 2 2 5 1 2 3 3 2 3 5 4 1 4 1 1 5 1 1 5 3 3 3 1 3 1 1 1 1
 1 5 6 5 2 3 5 1 2 6 4 2 3 3 2 2 1 5 1 1 3 2 4 5 3 1 1 1 1 3 2 2 1 1 2 5]


In [133]:
from sklearn.model_selection import KFold
kf=KFold(2,True)
for train,test in kf.split(X_train):
    print('train: %s, test: %s',train,test)

train: %s, test: %s [  0   1   2   6   9  10  13  14  15  17  19  21  24  27  30  35  36  37
  38  40  43  46  47  48  49  50  53  55  58  62  63  66  69  70  71  72
  73  75  76  77  80  85  86  87  89  90  91  92  93  94  95  99 104 106
 107 108 111 113 114 115 119 122 125 130 131 132 134 135 136 138 141 142
 145 146 150 152 155 157 158 160 163 164 167 168 170 172 174 177 178 180
 181 185 188 189 192 196 197 198 204 207 208 209 211 215 216 218 219 220
 223 224 225 226 233 234 235 236 237 239 241 243 247 248 249 250 251 252
 253 255] [  3   4   5   7   8  11  12  16  18  20  22  23  25  26  28  29  31  32
  33  34  39  41  42  44  45  51  52  54  56  57  59  60  61  64  65  67
  68  74  78  79  81  82  83  84  88  96  97  98 100 101 102 103 105 109
 110 112 116 117 118 120 121 123 124 126 127 128 129 133 137 139 140 143
 144 147 148 149 151 153 154 156 159 161 162 165 166 169 171 173 175 176
 179 182 183 184 186 187 190 191 193 194 195 199 200 201 202 203 205 206
 210 212 213 214 217 

In [122]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
r2=accuracy_score(Y_test,Y_pre)
r=confusion_matrix(Y_test,Y_pre)
e3=classification_report(Y_test,Y_pre)
print(r)
print('accuracy:',r2)
print(e3)

[[30  0  0  0  1  2]
 [ 0 15  0  1  0  2]
 [ 0  1 22  0  0  0]
 [ 0  4  0 13  1  0]
 [ 0  1  0  0 14  0]
 [ 0  0  0  0  0  3]]
accuracy: 0.8818181818181818
              precision    recall  f1-score   support

           1       1.00      0.91      0.95        33
           2       0.71      0.83      0.77        18
           3       1.00      0.96      0.98        23
           4       0.93      0.72      0.81        18
           5       0.88      0.93      0.90        15
           6       0.43      1.00      0.60         3

    accuracy                           0.88       110
   macro avg       0.82      0.89      0.84       110
weighted avg       0.91      0.88      0.89       110

